### PR TITLE
Fix hardcoded KA Lite version at mac OS X installer.

### LINKED ISSUE #426: OSX installer claims it's 0.16.0 not 0.16.9
## Summary

> The opening screen shows ￼
> version 0.16.0 rather than 0.16.9 
## Version
- Installer: OSX
- Version: 0.16.9
## Traceback or server.log snippet

```
None, and not relevant.
```
## Screenshots

Attached.
## How to reproduce
1. Run KA-Lite-0.16.9.pkg
2. Check the text in the opening screen.
   screen shot 2016-10-04 at 17 21 49

Please can you ensure the version number is consistent in the installer, the app and the installer.

### PR DESCRIPTION
**Pull request by mrpau-richard**
## Summary

> This will fix the hardcoded KA Lite version at the `.pkg`  installer.

## Issues addressed

Fixes #426

### CODE REVIEW

File: osx/build.sh [hunk 1]
```diff
@@ -368,6 +369,17 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+((STEP++))
+echo "Updating KA Lite installer version"
+KA_LITE_VERSION="$(kalite --version)"
+DOCS_PATH="$SCRIPTPATH/KA-Lite-Packages/docs"
+sed -i '' "13s/0.17.0/$KA_LITE_VERSION/g" "$DOCS_PATH/INTRODUCTION.rst.rtfd/TXT.rtf"
```
Comment (benjaoming) [inline osx/build.sh]: Here, you are replacing `0.17.0` - it would be better to change the files to have a placeholder like ``{{ KALITE_VERSION }}`` and replace this instead?

File: osx/build.sh [hunk 2]
```diff
@@ -368,6 +369,17 @@ if [ $? -ne 0 ]; then
...
+sed -i '' "12s/0.17.0/$KA_LITE_VERSION/g" "$DOCS_PATH/SUMMARY.rtfd/TXT.rtf"
+sed -i '' "12s/0.17.0/$KA_LITE_VERSION/g" "$DOCS_PATH/README.rst.rtf"
+if [ $? -ne 0 ]; then
```
Comment (benjaoming) [inline osx/build.sh]: This only tests the output of the previous command failed.

You can do the following to test all of it:

```bash
sed ... &&
sed ... &&
sed ... ||
(echo "failed to update installer version" && exit -1)
```

**Comment by mrpau-richard** [comment]
@benjaoming Thanks for reviewing this.  I've done fixing all your comments.
